[build]
  functions = "netlify/functions"
  publish = "."


[[redirects]]
  from = "/:user/certs/*"
  to = "/.netlify/functions/asset-proxy?user=:user&file=certs/:splat"
  status = 200


[[redirects]]
  from = "/:user/:file"
  to = "/.netlify/functions/asset-proxy?user=:user&file=:file"
  status = 200
